name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm run test

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Generate Build Info
      id: build_info
      run: |
        echo "BUILD_TIMESTAMP=$(date +%s)" >> $GITHUB_ENV
        echo "BUILD_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "Build timestamp: $BUILD_TIMESTAMP"
        echo "Build ID: $BUILD_ID"

    - name: Login to docker registry
      uses: docker/login-action@v3
      with:
        registry : harbor.m-loeffler.de
        username: ${{ secrets.HARBOR_ROBOT_NAME }}
        password: ${{ secrets.HARBOR_ROBOT_SECRET }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          harbor.m-loeffler.de/portfolio/todoapp01:latest
          harbor.m-loeffler.de/portfolio/todoapp01:${{ env.BUILD_ID }}
        build-args: |
          BUILD_TIMESTAMP=${{ env.BUILD_TIMESTAMP }}
          BUILD_ID=${{ env.BUILD_ID }}
          VITE_BASE_PATH=/todo/